# Generated by Django 4.0.4 on 2022-04-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Core',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputImage', models.ImageField(upload_to='uploads/')),
                ('outputImage', models.ImageField(default='frontend/src/default.jpg', upload_to='outputs/')),
            ],
        ),
    ]
