# Generated by Django 4.0.4 on 2022-04-30 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessingCore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
